language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t srikarrampally/docker-react -f Dockerfile.dev .

script:
  -   docker run -e CI=true  srikarrampally/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker"
  env: "Docker-env"
  bucket-name: xxxxx
  bucket-path: xxxxx
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECURE_KEY