language: generic 
sudo: required
services: 
  - docker

before-install:
  - docker build -t srikarrampally/docker-react -f Dockerfile.dev .

script:
  -   docker run -e CI=true  srikarrampally/docker-react npm run test -- --coverage